[
  {
    "logged_time": "2026-02-25T15:33:50+00:00",
    "user_name": "andrew.ji",
    "log_category": "library",
    "log_action": "load_content",
    "session_id": "2c05ce34-734c-44eb-bb25-e493c67af0ff",
    "id2": "/31_S.LSI/03 Report/YA Team/PCM Team/PCM_Inline_All_WECO",
    "email": "andrew.ji@samsung.com",
    "display_name": "Andrew Seungmin Ji",
    "dept_name": "Signal One - PCM",
    "cost_center_name": "Signal One",
    "title": "Engineer I",
    "nt_id": "aji5419",
    "bname": null,
    "gad_id": "andrew.ji",
    "FULL_NAME": "Andrew Ji",
    "STATUS_NAME": "Active"
  },
  {
    "logged_time": "2026-02-25T11:08:04+00:00",
    "user_name": "o.imasua",
    "log_category": "library",
    "log_action": "load_content",
    "session_id": "cd1b8c24-9385-4fa0-9fc3-fde07528f3e6",
    "id2": "/31_S.LSI/03 Report/YA Team/PCM Team/PCM_Inline_All_WECO",
    "email": "o.imasua@partner.samsung.com",
    "display_name": "oimasua9117",
    "dept_name": "Signal One - PCM",
    "cost_center_name": "Signal One",
    "title": "Technician II",
    "nt_id": null,
    "bname": null,
    "gad_id": null,
    "FULL_NAME": "Oziomachukwu Imasua",
    "STATUS_NAME": "Active"
  },
  {
    "logged_time": "2026-02-25T10:43:01+00:00",
    "user_name": "laura.galvan",
    "log_category": "library",
    "log_action": "load_content",
    "session_id": "5b16eeac-ba9e-490a-8c36-0cb1a3611571",
    "id2": "/31_S.LSI/03 Report/YA Team/PCM Team/PCM_Inline_All_WECO",
    "email": "laura.galvan@samsung.com",
    "display_name": "Laura D Galvan",
    "dept_name": "Signal One - PCM",
    "cost_center_name": "Signal One",
    "title": "Senior Technician",
    "nt_id": "lgalvan",
    "bname": "lgalvan",
    "gad_id": "laura.galvan",
    "FULL_NAME": "Laura D Galvan",
    "STATUS_NAME": "Active"
  },
  {
    "logged_time": "2026-02-25T09:46:42+00:00",
    "user_name": "t.valenzuela",
    "log_category": "library",
    "log_action": "load_content",
    "session_id": "532de82b-006d-48e7-96c1-759b4db0c63d",
    "id2": "/31_S.LSI/03 Report/YA Team/PCM Team/PCM_Inline_All_WECO",
    "email": "t.valenzuela@samsung.com",
    "display_name": "Tammie Valenzuela",
    "dept_name": "Signal One - PCM",
    "cost_center_name": "Signal One",
    "title": "Senior Technician",
    "nt_id": "tvalenzuela",
    "bname": "tvalenzuela",
    "gad_id": "t.valenzuela",
    "FULL_NAME": "Tammie Perkins",
    "STATUS_NAME": "Active"
  },
  {
    "logged_time": "2026-02-25T09:35:15+00:00",
    "user_name": "b.patschke",
    "log_category": "library",
    "log_action": "load_content",
    "session_id": "392314fc-83eb-4470-855d-8ef2e5d3978a",
    "id2": "/31_S.LSI/03 Report/YA Team/PCM Team/PCM_Inline_All_WECO",
    "email": "b.patschke@samsung.com",
    "display_name": "Brandon Patschke",
    "dept_name": "Signal One - PCM",
    "cost_center_name": "Signal One",
    "title": "Senior Technician",
    "nt_id": "bpatschke",
    "bname": "bpatschke",
    "gad_id": "b.patschke",
    "FULL_NAME": "Brandon L Patschke",
    "STATUS_NAME": "Active"
  },
  {
    "logged_time": "2026-02-25T07:23:02+00:00",
    "user_name": "s.wilson",
    "log_category": "library",
    "log_action": "load_content",
    "session_id": "28d6922b-0efe-4aab-867e-7bfb0c935d28",
    "id2": "/31_S.LSI/03 Report/YA Team/PCM Team/PCM_Inline_All_WECO",
    "email": "s.wilson@samsung.com",
    "display_name": "Shawn E Wilson",
    "dept_name": "Signal One - PCM",
    "cost_center_name": "Signal One",
    "title": "Senior Technician",
    "nt_id": "swilson",
    "bname": "swilson",
    "gad_id": "s.wilson",
    "FULL_NAME": "Shawn E Wilson",
    "STATUS_NAME": "Active"
  },
  {
    "logged_time": "2026-02-25T04:59:15+00:00",
    "user_name": "m.srey",
    "log_category": "library",
    "log_action": "load_content",
    "session_id": "13bd1681-de50-40cc-8bfe-0fc1fbe5ab6b",
    "id2": "/31_S.LSI/03 Report/YA Team/PCM Team/PCM_Inline_All_WECO",
    "email": "m.srey@samsung.com",
    "display_name": "Maline Srey",
    "dept_name": "Signal One - PCM",
    "cost_center_name": "Signal One",
    "title": "Senior Technician",
    "nt_id": "msrey",
    "bname": "msrey",
    "gad_id": "m.srey",
    "FULL_NAME": "Maline Srey",
    "STATUS_NAME": "Active"
  },
  {
    "logged_time": "2026-02-25T04:54:15+00:00",
    "user_name": "d.imhanria",
    "log_category": "library",
    "log_action": "load_content",
    "session_id": "5079ad00-011e-4576-80d6-8b72475e45b3",
    "id2": "/31_S.LSI/03 Report/YA Team/PCM Team/PCM_Inline_All_WECO",
    "email": "d.imhanria@partner.samsung.com",
    "display_name": "David Imhanria",
    "dept_name": "Signal One - PCM",
    "cost_center_name": "Signal One",
    "title": "Technician II",
    "nt_id": null,
    "bname": null,
    "gad_id": null,
    "FULL_NAME": "David Imhanria",
    "STATUS_NAME": "Active"
  },
  {
    "logged_time": "2026-02-20T09:17:39+00:00",
    "user_name": "h.hannan",
    "log_category": "library",
    "log_action": "load_content",
    "session_id": "2025e7fe-6450-416c-9f1f-88a3cec47359",
    "id2": "/31_S.LSI/03 Report/YA Team/PCM Team/PCM_Inline_All_WECO",
    "email": "h.hannan@samsung.com",
    "display_name": "Heather Lindsey Hannan",
    "dept_name": "Digital Solutions - Data Science",
    "cost_center_name": "Digital Solutions",
    "title": "Engineer II",
    "nt_id": "hhannan4026",
    "bname": null,
    "gad_id": "h.hannan",
    "FULL_NAME": "Heather Hannan Samra",
    "STATUS_NAME": "Active"
  },
  {
    "logged_time": "2026-02-14T09:39:52+00:00",
    "user_name": "mp.rodriguez",
    "log_category": "library",
    "log_action": "load_content",
    "session_id": "e806d512-9cce-4744-8046-102a5b853a13",
    "id2": "/31_S.LSI/03 Report/YA Team/PCM Team/PCM_Inline_All_WECO",
    "email": "mp.rodriguez@samsung.com",
    "display_name": "Michael Pete Rodriguez",
    "dept_name": "Signal One - PCM",
    "cost_center_name": "Signal One",
    "title": "Master Technician",
    "nt_id": "mrodriguez1",
    "bname": "mrodriguez1",
    "gad_id": "mp.rodriguez",
    "FULL_NAME": "Michael Pete Rodriguez",
    "STATUS_NAME": "Active"
  },
  {
    "logged_time": "2026-02-05T17:15:02+00:00",
    "user_name": "dmoody",
    "log_category": "library",
    "log_action": "load_content",
    "session_id": "3ed3976a-dcab-4cbe-81b7-3a82dcfd8b3f",
    "id2": "/31_S.LSI/03 Report/YA Team/PCM Team/PCM_Inline_All_WECO",
    "email": "d.moody@samsung.com",
    "display_name": null,
    "dept_name": "Digital Solutions",
    "cost_center_name": "Digital Solutions",
    "title": "Staff Engineer I TR",
    "nt_id": "dmoody",
    "bname": "dmoody",
    "gad_id": "d.moody",
    "FULL_NAME": "Daniel Drummond Moody",
    "STATUS_NAME": "Active"
  }
]
